artifact_uri: file:///Users/wesley/Desktop/wooshikwon/wmtp/mlflow_runs/674261730469747670/07e2de52beae4900a26b0bad330512bf/artifacts
end_time: 1758696328898
entry_point_name: ''
experiment_id: '674261730469747670'
lifecycle_stage: active
run_id: 07e2de52beae4900a26b0bad330512bf
run_name: mtp baseline_quick
source_name: ''
source_type: 4
source_version: ''
start_time: 1758696292333
status: 3
tags: []
user_id: wesley
