artifact_uri: file:///Users/wesley/Desktop/wooshikwon/wmtp/mlflow_runs/674261730469747670/a5a8760a37f54a61af0514ccead5279f/artifacts
end_time: 1758697883058
entry_point_name: ''
experiment_id: '674261730469747670'
lifecycle_stage: active
run_id: a5a8760a37f54a61af0514ccead5279f
run_name: device_test
source_name: ''
source_type: 4
source_version: ''
start_time: 1758697868991
status: 3
tags: []
user_id: wesley
