"""Type stubs for sentencepiece library"""

from typing import List, Optional, Union

class SentencePieceProcessor:
    def __init__(self, model_file: Optional[str] = None) -> None: ...
    def Load(self, model_file: str) -> None: ...
    def LoadFromSerializedProto(self, serialized_model_proto: bytes) -> None: ...
    def encode(
        self,
        text: str,
        out_type: type = int,
        add_bos: bool = False,
        add_eos: bool = False
    ) -> List[int]: ...
    def decode(self, ids: List[int]) -> str: ...
    def get_piece_size(self) -> int: ...
    def bos_id(self) -> int: ...
    def eos_id(self) -> int: ...
    def pad_id(self) -> int: ...
    def unk_id(self) -> int: ...