# Environment Configuration for WMTP Fine-Tuning Framework
# This file contains environment-specific settings

# Project metadata
project: "mtp_ft"
seed: 42

# Storage configuration
storage:
  mode: "local"  # Options: local, s3
  # Uncomment and configure for S3 storage
  # s3:
  #   bucket: "wmtp-artifacts"
  #   region: "ap-northeast-2"
  #   prefix: "mtpfw/"

# Path configurations
paths:
  models:
    base_local: "models/7b_1t_4"
    rm_local: "models/Llama_3_8B_RM"
    ref_local: "models/sheared_llama_1.3B"
  datasets:
    mbpp_local: "dataset/mbpp"
    contest_local: "dataset/contest"
  cache: ".cache"

# MLflow configuration
mlflow:
  experiment: "mtp/wmtp"
  # For local development
  tracking_uri: "file:///tmp/mlflow"
  registry_uri: "file:///tmp/mlflow"
  # For production with S3
  # tracking_uri: "s3://wmtp-artifacts/mlflow"
  # registry_uri: "s3://wmtp-artifacts/mlflow"

# Launcher configuration
launcher:
  target: "local"  # Options: local, vessl
  resources:
    gpus: 4
    gpu_type: "A100"
    cpus: 32
    memory_gb: 256
    disk_gb: 500

# Device and distributed training configuration
devices:
  mixed_precision: "bf16"  # Options: bf16, fp16, fp32
  fsdp:
    enabled: true
    auto_wrap: true
    activation_ckpt: true
    sharding: "full"  # Options: full, shard_grad_op
