# M3 MacBook Pro 실험 환경 설정
# 64GB RAM, Metal GPU를 활용한 빠른 실험용 설정

project: "wmtp_experiment"
seed: 42

# 로컬 스토리지만 사용 (빠른 실험)
storage:
  mode: "local"

# 경로 설정 - 기존 모델과 데이터셋 활용
paths:
  models:
    base_local: "models/7b_1t_4"              # Facebook MTP 모델
    rm_local: "models/Llama_3_8B_RM"          # Reward 모델 (Critic용)
    ref_local: "models/codellama_7b_python"   # Reference 모델 (Rho-1용)
  datasets:
    mbpp_local: "dataset/mbpp"
    contest_local: "dataset/contest"
  cache: ".cache"

# MLflow 추적 설정 - 로컬 디렉토리 기반 (M3 MacBook Pro 최적화)
mlflow:
  experiment: "wmtp/quick_comparison"
  tracking_uri: "${MLFLOW_TRACKING_URI:-file://./mlflow_runs}"
  registry_uri: "${MLFLOW_REGISTRY_URI:-file://./mlflow_runs}"

# M3 MacBook Pro 리소스 설정
launcher:
  target: "local"
  resources:
    gpus: 1        # M3 GPU
    gpu_type: "M3"
    cpus: 12       # M3 Pro 성능 코어
    memory_gb: 64
    disk_gb: 100

# 디바이스 설정 - 로컬 개발용 CPU 모드 (Facebook MTP 하드코딩 우회)
devices:
  compute_backend: "cpu"    # CPU로 안전한 로컬 테스트
  device_ids: null          # CPU는 디바이스 ID 불필요
  mixed_precision: "fp32"   # CPU는 fp32가 가장 안정적
  fsdp:
    enabled: false          # CPU에서는 FSDP 비활성화
    auto_wrap: false
    activation_ckpt: false
    sharding: "full"
