# MacBook M3 Test Configuration for WMTP Pipeline Verification
# Optimized for Apple Silicon with MPS (Metal Performance Shaders)
# Schema-compliant configuration

# Project metadata
project: "wmtp_m3_test"
seed: 42

# Storage configuration - local only for testing
storage:
  mode: "local"  # Options: local, s3

# Path configurations
paths:
  models:
    # Use test MTP wrapper instead of large 7B model
    base: "princeton-nlp/Sheared-LLaMA-2.7B"  # Will be wrapped with MTP heads
    rm: "models/Starling-RM-7B-alpha"  # Can skip for initial test
    ref: "distilgpt2"  # Tiny reference model for Rho1 testing
  datasets:
    mbpp: "dataset/mbpp"
    contest: "dataset/contest"

# MLflow configuration - local tracking
mlflow:
  experiment: "wmtp/m3_test"
  tracking_uri: "file:///tmp/mlflow_m3"
  registry_uri: "file:///tmp/mlflow_m3"

# Launcher configuration (필수 필드)
launcher:
  target: "local"  # Local execution on M3
  resources:
    gpus: 1  # Single GPU (MPS)
    gpu_type: "mps"  # Metal Performance Shaders
    cpus: 8  # M3 CPU cores
    memory_gb: 64  # System memory
    disk_gb: 100  # Available disk

# Device configuration for MacBook M3
devices:
  compute_backend: "mps"  # Metal Performance Shaders
  mixed_precision: "fp32"  # MPS works best with fp32 initially
  fsdp:
    enabled: false  # Disable FSDP for single GPU
    auto_wrap: false
    activation_ckpt: false
    sharding: "full"  # Use 'full' even when disabled