# Production Recipe - MTP Baseline Algorithm
# Uniform weighting for Multi-Token Prediction on A100x2

# Run metadata
run:
  name: "prod_mtp_baseline"
  tags:
    - "production"
    - "vessl"
    - "baseline"
    - "mtp"
    - "a100"

# Data configuration
data:
  train:
    sources: ["mbpp", "contest"]
    max_length: 2048
    batch_size: 4  # Per GPU: 4 x 2 = 8 total
    pack_sequences: true
    num_workers: 8
  eval:
    sources: ["mbpp", "humaneval"]
    max_length: 2048
    batch_size: 4
    pack_sequences: false
    num_workers: 4

# Training configuration
train:
  algo: "baseline-mtp"  # Uniform weighting
  full_finetune: true
  max_steps: 10000
  eval_interval: 500
  save_interval: 1000
  # checkpointing moved to config.paths.checkpoints in Phase 2

# Optimizer configuration
optim:
  optimizer: "adamw"
  lr: 2.0e-5
  weight_decay: 0.01
  betas: [0.9, 0.999]
  grad_clip: 1.0
  scheduler: "cosine"
  warmup_ratio: 0.03

# Loss configuration - baseline (uniform weights)
loss:
  weight_norm: "none"
  lambda: 0.001
  weight_temperature: 1.0
  epsilon: 1.0e-8
  max_weight: 1.01

# Evaluation configuration
eval:
  protocol: "meta-mtp"
  sampling:
    temperature: 0.7
    top_p: 0.9
    n: 20  # For pass@k evaluation
  metrics:
    - "mbpp_exact"
    - "humaneval_exact"
    - "contest_exact"