# Production Recipe - Rho1 WMTP Algorithm
# Reference CE comparison based dynamic weighting on A100x2

# Run metadata
run:
  name: "prod_rho1_wmtp"
  tags:
    - "production"
    - "vessl"
    - "rho1"
    - "wmtp"
    - "a100"
    - "reference-ce"

# Model configuration
model:
  base_id: "mtp-7b-1t-4"  # Facebook MTP 7B model
  tokenizer_type: "hf"
  tokenizer_pad_side: "right"
  mtp:
    n_heads: 4
    horizon: 4

# Training configuration
train:
  algo: "rho1-wmtp"  # Reference CE comparison based weighting
  full_finetune: true
  max_steps: 10000
  eval_interval: 500
  save_interval: 1000
  checkpointing:
    save_interval: 1000
    keep_last: 5
    save_final: true

# Optimizer configuration
optim:
  optimizer: "adamw"
  lr: 2.0e-5
  weight_decay: 0.01
  betas: [0.9, 0.999]
  grad_clip: 1.0
  scheduler: "cosine"
  warmup_ratio: 0.03

# Data configuration
data:
  train:
    sources: ["mbpp", "contest"]
    max_length: 2048
    batch_size: 4  # Per GPU: 4 x 2 = 8 total
    pack_sequences: true
    num_workers: 8
  eval:
    sources: ["mbpp", "humaneval"]
    max_length: 2048
    batch_size: 4
    pack_sequences: false
    num_workers: 4

# Loss configuration - rho1 with reference comparison
loss:
  weight_norm: "softmax"
  lambda: 0.01
  temperature: 1.0
  epsilon: 1.0e-8
  max_weight: 10.0
  # Rho1 specific parameters
  rho_alpha: 0.1    # Weight for reference CE difference
  rho_beta: 1.0     # Scale factor for CE difference
  min_ce_diff: 0.01 # Minimum CE difference threshold

# Evaluation configuration
eval:
  protocol: "meta-mtp"
  sampling:
    temperature: 0.7
    top_p: 0.9
    n: 20  # For pass@k evaluation
  metrics:
    - "mbpp_exact"
    - "humaneval_exact"
    - "contest_exact"