artifact_uri: file:///Users/wesley/Desktop/wooshikwon/wmtp/mlflow_runs/674261730469747670/54fa38d2f2a24874b2ab9de2cc939713/artifacts
end_time: null
entry_point_name: ''
experiment_id: '674261730469747670'
lifecycle_stage: active
run_id: 54fa38d2f2a24874b2ab9de2cc939713
run_name: mtp baseline_quick_af0b2518
source_name: ''
source_type: 4
source_version: ''
start_time: 1758698881462
status: 1
tags: []
user_id: wesley
