artifact_uri: file:///Users/wesley/Desktop/wooshikwon/wmtp/mlflow_runs/674261730469747670/7cd00fde27434f1d96f4f6bd0115b49d/artifacts
end_time: 1758695905852
entry_point_name: ''
experiment_id: '674261730469747670'
lifecycle_stage: active
run_id: 7cd00fde27434f1d96f4f6bd0115b49d
run_name: mtp baseline_quick
source_name: ''
source_type: 4
source_version: ''
start_time: 1758695885687
status: 3
tags: []
user_id: wesley
